version: "3.9"
services:

  backend:
    env_file:
      - .env
  

    build:
      context: backend/.
      dockerfile: Dockerfile
      target: development
    stdin_open: true
    tty: true
    command: sh -c "python ./main/manage.py migrate && python ./main/manage.py runserver 0.0.0.0:${PORT}"
    volumes:
      - ./backend:/app
    ports:
      - ${PORT}:${PORT}
   

  frontend:
    image: node:20-alpine
    command: sh -c "npm install && npm install react-popup && npm run start"
    working_dir: '/app'
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    ports:
      - 3000:3000
   

