# Generated by Django 4.1.2 on 2022-11-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_tag_question_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="name",
            field=models.CharField(
                choices=[
                    ("ES", "ES"),
                    ("BD", "BD"),
                    ("COMP", "COMP"),
                    ("IPRP", "IPRP"),
                    ("POO", "POO"),
                    ("PPP", "PPP"),
                    ("RC", "RC"),
                    ("SI", "SI"),
                    ("SO", "SO"),
                    ("TC", "TC"),
                    ("TI", "TI"),
                ],
                default="ES",
                max_length=3,
            ),
        ),
    ]
